# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    container_name: database.dev
    command: mysqld --user=root --verbose
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "taskmanager"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"